### ISSUE TITLE
Option to disable for local dev?

### ISSUE THREAD

**Issue by mtwomey** [serverless-heaven/serverless-webpack#1022]
I do my dev / test work locally and debug with the chrome debugger. I prefer un-webpacked files for use during dev and when debugging. Is it possible to disable this plugin either via a custom value in serverless.yml or a command line option? Right now I'm constantly commenting / uncommenting it from my serverless.yml.

**Comment by vicary** [comment]
In theory Chrome debugger, or node.js debug mode, should be able to understand source-maps, have you tried enabling it in your `webpack.config.js`?

**Comment by mtwomey** [comment]
Yes, it can. It's just faster and easier to not have to deal with that. It also helps me isolate issues to my code without needing to think about webpack until I'm ready to do so.

**Comment by vicary** [comment]
This makes no sense for TypeScript projects, and to align the internal workflow for both projects, even javascript projects will have to run off of the `.webpack` directory instead of the actual source file.

I would argue that at server-side there is no inherent benefits in bundling if you are already writing in JavaScript, but I am curious about the reasons you are using webpack.
