### ISSUE TITLE
Unexpected Token ...

### ISSUE THREAD

**Issue by radelcom** [serverless-heaven/serverless-webpack#233]
# This is a Bug Report

## Description
I started getting this error message when doing `sls deploy`. I was digging around and narrowed it down. It seems like dependent on which node version I am using. I am using [nvm](https://github.com/creationix/nvm) as my node version manager. If I use node v6.10.3, I get this issue and if I switched to node v8.4.0, all goes away and deploys successfully. 

I guess follow up question is, is it ok to use node v8.4.0 during development and wont have impact to the actual supported node v6.10 version in AWS when serverless is deployed?

Any input is greatly appreciated. tx in advance!

Similar or dependent issue(s):
* #126
* #193

## Additional Data

serverless: v1.21.1
serverless-webpack: v3.0.0
webpack: v3.0.0
node: v6.10.3

```
Serverless: WARNING: Plugin ServerlessWebpack uses deprecated hook before:deploy:createDeploymentArtifacts
Serverless: WARNING: Plugin ServerlessWebpack uses deprecated hook after:deploy:createDeploymentArtifacts
 
  Syntax Error -------------------------------------------
 
     Unexpected token ...
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at ServerlessWebpack.validate
```

**Comment by HyperBrain** [comment]
Hi @radelcom , thanks for submitting the issue ;-)

The warnings are unrelated to the issue, and the property 1 bug too - these were/are different ones.

But it is strange that the Node version makes a difference. There should be no code at all in the plugin that uses functionality that is only available in Node 8 (we use Node 6 everywhere at work to replicate the behavior on the AWS Lambda runtime and I never saw the issue).

Can you try to upgrade or downgrade the SLS version, just to make sure that it is independent from that? I remember that there was a discussion of using graceful-fs in SLS, which impacts all plugins loaded in the SLS process, but I'm not sure if that can have anything to do with the issue.

As it already crashes during a `require()` here are the imported modules from `validate()`. One of them must cause the issue during the import:
```js
const BbPromise = require('bluebird');
const path = require('path');
const fse = require('fs-extra');
const glob = require('glob');
const lib = require('./index');
const _ = require('lodash');
```

What I can try to do is, to update these dependencies to the most recent versions and we can check if the problem is gone.

**Comment by HyperBrain** [comment]
Just another guess: `validate()` loads the webpack config file. It could also be an error coming from that load operation. Can you check if there are any constructs/dependencies in your webpack config file that are not Node 6 compatible? If possible, can you post the webpack config?

**Comment by HyperBrain** [comment]
I added an extra log line in case the configuration file cannot be loaded in #234 , so that it is clear, if an error is located in the config or in the plugin.

Can you try to use the PR version and check if the crash is originating from the plugin or the config?
Just use: `"serverless-webpack": "serverless-heaven/serverless-webpack#improve-error-config-load"`

**Comment by radelcom** [comment]
Hi @HyperBrain,

Thanks for the speedy response. It turns out, I think it is more related to the boilerplate template I was using [serverless-es7](https://github.com/AnomalyInnovations/serverless-es7). Instead, I followed the sample setup in [babel-dynamically-entries](https://github.com/serverless-heaven/serverless-webpack/tree/master/examples/babel-dynamically-entries) and it seems to be working fine now in node v6.10.x

**Comment by HyperBrain** [comment]
Glad to hear that the issue is solved 👍 . I will merge the log changes I did so that they are in the next release. Then it will show the reason for these issues right away.
