### ISSUE TITLE
Support `webpack.config.js` exporting a function

### ISSUE THREAD

**Issue by jazen** [serverless-heaven/serverless-webpack#262]
# This is a Bug Report / Feature Proposal

It's both I guess.

## Description

For bug reports:
* What went wrong?

I followed [this guide](https://survivejs.com/webpack/developing/automatic-browser-refresh/) and realized that a `webpack.config.js` [exporting a function is not yet supported](https://github.com/serverless-heaven/serverless-webpack/blob/master/lib/validate.js#L96-L108).

* What did you expect should have happened?

It should check whether the default export is a function and call it appropriately passing in the `--env` parameter.

* What was the config you used?

Nothing special.

```
const commonConfig = { ... }

module.exports = env => {
  console.log('env', env);
  return commonConfig;
}
```

* What stacktrace or error message from your provider did you see?

For feature proposals:

* It provides more flexibility in customizing your webpack configuration via the CLI.

## Additional Data

* ***Serverless-Webpack Version you're using***:

```
"serverless-webpack": "^3.0.0",
```

* ***Webpack version you're using***:
```
./node_modules/.bin/webpack --version
3.8.1
```
* ***Serverless Framework Version you're using***:
```
sls --version
1.22.0
```

* ***Operating System***:

OSX High Sierra

**Comment by HyperBrain** [comment]
Hi @jazen , thank you for submitting the feature request.

I'm not really sure how much value the possibility of exporting a function would add and which other risks it introduces.
As the plugin has full access to the Serverless state and options (via `slsw.lib.serverless` and `slsw.lib.options`) you can create your config fully dynamically depending on anything within the framework. E.g. you can add a "--env" switch to the Serverless command line and easily evaluate it with `slsw.lib.options.env` afterwards and change the exported configuration object properly.
The plugin even _modifies_ the configuration and prepares it, so that it will work within the Serverless ecosystem. Having a dynamic object that it returned from a function might mess up things.

It looks to me that the instructions are merely targeted for a manual webpack configuration setup that is triggered from npm. As said above, we run in a closed framework as plugin and it already offers means to add arbitrary data through serverless.

What do you think?

**Comment by jazen** [comment]
Thanks for the quick answer! Re-reading the README I see this part:

> The lib export also provides the `serverless` and `options` properties, through which you can access the Serverless instance and the options given on the command-line.
>
> This enables you to have a fully customized dynamic configuration, that can evaluate anything available in the Serverless framework. There are really no limits.

But unfortunately I don't understand how should work — could you please provide a few examples?

I tried adding in `webpack.config.js`:

    const slsw = require('serverless-webpack');
    console.log(JSON.stringify(slsw , null, 2))

and passing `sls webpack --env.foo 3` and adding a few custom variables in `serverless.yml` under the `provider.environment` and the `service` key but I always get `undefined` in the build output.

What am I misunderstanding here?

**Comment by HyperBrain** [comment]
The keys you specified should be available with `slsw.lib.serverless.service.provider.environment` and if you define anything in `custom` in your serverless.yml, it will be at `slsw.lib.serverless.service.custom`.

Your given option should be `slsw.options['env.foo']`.

@serverless-heaven/serverless-webpack-contributors Any ideas?

**Comment by franciscocpg** [comment]
I do agree @HyperBrain 
It's the best way to go right now.

**Comment by jazen** [comment]
@HyperBrain Aah — I didn't realize the `slsw` import/export is a function and wondered why attempting to `JSON.stringify` it results in `undefined`.

So yes that works and I guess there's no need to support the function export from `webpack` here. 

Feel free to close the issue!

PS: Btw, the CLI argument above shows up in `slsw.lib.options.env.foo` for me.

**Comment by HyperBrain** [comment]
@jazen , thank you for the feedback. I'll close the issue then.

> slsw.lib.options.env.foo

Did not know that the option parsing of SLS is so advanced 😄
