### ISSUE TITLE
Support loading `webpack.config.babel.js`

### ISSUE THREAD

**Issue by crubier** [serverless-heaven/serverless-webpack#289]
# This is a Bug Report

## Description

Webpack supports having a `webpack.config.babel.js` file written in es6 instead of a `webpack.config.js` written in es5. 

However this does not work with serverless-webpack.

**Comment by HyperBrain** [comment]
Hi @crubier ,

thanks for the suggestion.
Yes, that does not work, because the webpack CLI does allow that, but with using the webpack API you (here the serverless-webpack plugin) have to provide the config to the API. That means, that the plugin loads the file (it actually has to because it has to inject some important configurations that are implied by the Serverless and the project configuration).

Loading an ES6 file (using require) would also mean, that the plugin had to use babel-register to get the ES6 file compiled on the fly. Actually that is not a good idea, because we would pollute our host (i.e. Serverless) and inject a babel transparent compile into every require done by Serverless which might lead to unpredictable behavior. Additionally babel-register can only be loaded once and will throw an exception on every subsequent try -> so neither user code executed with `sls invoke local` nor Serverless or any other plugin must load babel-register if we do.

Imo supporting this feature would introduce lots of drawbacks and will quite likely also introduce incompatibilities.

**Comment by crubier** [comment]
Hi, thank you for the quick reply. 

Your answer definitely makes sense, but yep, the whole situation is not ideal. 

I chose to not use this plugin because of this. I prefer to have to build « manually » with webpack and then deploy without serverless-webpack rather than have a single ugly old school non-Babel file in my codebase.

I understand this is not at all your fault, but if you ever have an alternative solution for me, I would really appreciate it !

Thanks !

**Comment by HyperBrain** [comment]
If there is any other option than using babel-register, or if there is a way to have it somehow isolated, I'm fully willing to have the feature done... Maybe someone has an idea or a solution.

I also already though of a ad-hoc compile of the file ...

**Comment by HyperBrain** [comment]
I'll close this one for now, but keep it in mind.
