### ISSUE TITLE
npm link (symlink) not webpacking

### ISSUE THREAD

**Issue by josephleehunsaker** [serverless-heaven/serverless-webpack#294]
This may be a bug, or I may be doing it incorrectly.

I have an npm package I maintain at work, and I want to make changes and test them locally. npm link is perfect for this. However, when I run sls webpack, the linked npm package is not using my local copy. 

Any idea why this is the case?

**Comment by HyperBrain** [comment]
Hi @josephleehunsaker . Unfortunately this is currently not supported, because `serverless-webpack` will install the needed packages during the deployment.

However, there is #281 which will enable support for local packages (e.g. installed with `npm link ../../mymodule`. Currently the PR is blocked, because there is a bug in npm that has to be resolved first.

**Comment by MarkRobertJohnson** [comment]
So is this fixed?  I am still having an issue with linked npm modules.

  Command failed: npm ls -prod -json -depth=1
npm ERR! invalid: @ls/ls-common-lib@1.0.0 C:\dev\@ls\ls-common-lib

**Comment by HyperBrain** [comment]
Hi @MarkRobertJohnson , can you try if a local install `npm install <relative_path>` works and only the linked modules fail?

Somehow it seems the command `npm ls -prod -json -depth=1` fails when the plugin tries to execute it.
Can you try to execute it manually? It might be, that there is something broken with the node_modules folder.

**Comment by MarkRobertJohnson** [comment]
@HyperBrain Yes, installing from local path is fine, no errors and deployment works fine.  This issue occurs only with linked npm modules (we use npm link'd modules because it speeds up the development loop).  This does appear to be a bug with the "npm ls" command, it will throw that error if there are any npm link'd modules.

Just a note, serverless offline works fine (it too is using serverless-webpack), I wonder what the difference is?

**Comment by HyperBrain** [comment]
For Serverless-offline together with the webpack plugin the packaging step is not done and the compiled code is executed locally, but the node modules are fetched from the local node modules folder.

In case of a deployment, the node modules are separately installed as detected by webpack. The `npm ls` is in this case needed to detect first and second level dependencies that might have been created by webpack bundling a first level dependency.
We should check if this error with `npm ls` is already reported in the npm GitHub repository and link the issue here.

**Comment by HyperBrain** [comment]
@MarkRobertJohnson BTW: Did you make tests with different npm versions. What we have seen (and for what the workaround in #281 is good for) is that there is an increased bug amount in all NPM versions >= 5.5 regarding linked, local and locked modules.

**Comment by rynop** [comment]
Is there a workaround for this?  Stuck on a private repo of mine, not using npm link.  Just defining it in my `package.json`

```
"core-framework": "git+ssh://git@github.com:MYORG/core-framework.git",
```

Gettin following when I `sls deploy`
```
Error: Command failed: npm ls -prod -json -depth=1
npm ERR! invalid: core-framework@1.0.34 /Users/ethan/projects/a/node_modules/core-framework
```

**Comment by HyperBrain** [comment]
@rynop Which npm version do you use? With recent ones we had no problems with GIT references. Additionally, it might help to force delete the npm cache with `npm cache clean --force`

**Comment by rynop** [comment]
Tried `5.3.0` and `6.1.0`.  `npm update` worked for some reason.

**Comment by kernwig** [comment]
Why is this closed? npm linked packages still can't be deployed. The referenced version gets deployed by serverless-webpack, rather than the linked one.

$ node -v && npm -v && sls -v && npm list |grep serverless
v8.11.3
6.4.0
1.30.1
serverless-offline@3.25.8
serverless-plugin-export-endpoints@0.1.2
serverless-webpack@5.2.0

**Comment by abdulghani** [comment]
in 2021, in CI this issue still happen
doing `npm ls -prod -json -depth=1` resolves error
```
"problems": [
    "missing: sibling-package@1.0.0, required by sibling-package@1.0.0"
],
```

my current workaround is removing `CI` from `process.env`
and builds okay

**Comment by abdulghani** [comment]
in 2021, in CI this issue still happen
doing `npm ls -prod -json -depth=1` resolves error
```
"problems": [
    "missing: sibling-package@1.0.0, required by main-package@1.0.0"
],
```

my current workaround is removing `CI` from `process.env`
and builds okay
