### ISSUE TITLE
`Service files not changed. Skipping deployment...` not happening with serverless-webpack

### ISSUE THREAD

**Issue by tommedema** [serverless-heaven/serverless-webpack#303]
Serverless (native) will not re-deploy functions when they have not changed. You'll see something like:

```
Serverless: Packaging service...
Serverless: Service files not changed. Skipping deployment...
```

However, when using `serverless-webpack`, source files are always recompiled and redeployed, even when they have not changed.

Are you open to the idea of checking if the files pre-packaging are the same (by comparing a checksum)? How does serverless do this?

I suppose the best way would be to compute the checksum, and then compare it against a checksum saved as a stack export / output variable of the deployment bucket. This would be better than to compare against the `.serverless` folder because this state is not the same on other developers' machines.

**Comment by HyperBrain** [comment]
@tommedema Serverless-webpack is a package only plugin, i.e. it does not run during any deployment step (and imo it should not). Serverless-webpack is provider independent and must have no knowledge about any provider specific deployment mechanisms.

Serverless does check the checksums of the generated zip files and will skip them if the hashes are the same - also together with serverless-webpack. If the same sources are recompiled, you end up with the same zip files.

**Comment by tommedema** [comment]
@HyperBrain that makes sense.

Still, at least it should not re-package if the source files have not changed, right?

**Comment by HyperBrain** [comment]
> Still, at least it should not re-package if the source files have not changed, right?

I'm not sure if that is possible, so that it is deterministic. There are a lot of webpack plugins that can change the output even if there is no changes in the sources. E.g. you can use the define plugin to create real constants with a random value to have a different static id in your code per deployment.
There is no source change, but the output from the webpack compile is different. Another issue is, that the source files might be not easy to detect - using the elm-loader is an example, not to forget local dependencies (they would have to be hashed too) or github dependencies (in case you bundle them). The fact that webpack is a compiler, predict what exactly will happen is most likely not possible. These are all problems that native serverless does not face.

> By the way, when I use this plugin, it always causes a re-deployment. For some reason the built files are always different, even when using the same source files.

That's strange. As long as no plugins are used that change the compile output in any way or different dependencies (without using a package-lock file), the same zip files should be generated. I tested that with some small projects (for the bigger ones some of the function zips where the same) with `serverless package`.
If Serverless does not skip the uploads to S3 for identical zip files, it might be a bug in there (there is currently one about multiple zip uploading for service packaging in some circumstances).

**Comment by tommedema** [comment]
Thanks, I see. I will see if I can reproduce the repackaging in a smaller test case.
