### ISSUE TITLE
Cannot define webpack configuration as typescript

### ISSUE THREAD

**Issue by chanlito** [serverless-heaven/serverless-webpack#404]
I created a `webpack.config.ts` file, but the plugin seems to ignore it.

**Comment by HyperBrain** [comment]
Can you please use the issue template that is shown when opeining an issue and put in all information that can help to reproduce and analyze the issue? Examples are: your config.ts file, the used webpack and plugin versions, etc.

However, specifying a ts config should be possible because the plugin automatically should use `ts-node` in this case. With more informatino I could try to find it.

**Comment by chanlito** [comment]
BTW @HyperBrain also consider updating current ts-node version is way behind. I'll try to create a repo.

**Comment by HyperBrain** [comment]
Thanks for the info. As I do not use TS in our projects, I did not recognize that. Do you know if there is anything that has to be checked when updating ts-node? I saw that it is a double major version jump.

**Comment by chanlito** [comment]
Yes, ts-node v6 has typescript-checking by default, which for some people is good and some is bad, like me I just want transpileOnly for faster builds because vscode editor show typescript errors pretty well already.

**Comment by chanlito** [comment]
I create a repo https://github.com/chanlito/serverless-typescript-template you can clone it and try.

**Comment by martinjlowm** [comment]
It works fine here (apart from a syntax error in `tsconfig.json` and the following)... with `serverless.yml`'s `webpackConfig` pointing to `webpack.config.ts`.

`serverless-webpack` does not appear to support `export default`-config at this time. See https://github.com/serverless-heaven/serverless-webpack/blob/016415926b0d0814fa94638e390f59eca3713d61/lib/validate.js#L114

It results in
```
{
  default: {
    ...config
  }
}
```

rather than
```
{
  ...config
}
```

You may use `module.exports = config` instead.

**Comment by HyperBrain** [comment]
@chanlito Can this be closed?
