### ISSUE TITLE
Allow to skip sourcemaps from the package

### ISSUE THREAD

**Issue by jaydp17** [serverless-heaven/serverless-webpack#470]
# This is a Feature Proposal

## Description
Allow filtering files after webpack runs but before packaging.

When you have source maps enabled, source-maps get bundled in the deployment package (zip file) along with the compiled js bundle.

If you're using a separate Error Reporting system like [Sentry](https://sentry.io) you don't need to upload the source maps in the package zip file. This reduces the final package zip size by ~ 50%.

#### Why not disable source-maps in webpack?
If we do that, then we'll have to build once again after packaging/deploy to get the source-maps to upload to Sentry.

_**P.S. I don't mind sending a PR for this, I just want to use this issue to discuss the feature**_

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.2.0
* ***Webpack version you're using***: 4.28.2
* ***Serverless Framework Version you're using***: 1.35.0
* ***Operating System***: macOS
* ***Stack Trace (if available)***:

**Comment by ouamer-dahmani** [comment]
Hello guys!
Any progress on this issue?

My webpack config generates map files as well as report.html files from the bundle analyzer plugin. These get bundle more than doubling the size of my lambda packages.

One workaround I tried was to force the path of source map to a different folder. However this does not work for the bundle size report with multiple entry points as it is not compatible with qualifiers such as [file].

I also tried adding entries in a .gitignore file so that npm does not package them but that does not work either.

It would be great if I could just tell serverless webpack to ignore those files.

Thanks!

**Comment by MikeRippon** [comment]
> 
> 
> Hello guys!
> Any progress on this issue?
> 
> My webpack config generates map files as well as report.html files from the bundle analyzer plugin. These get bundled thus more than doubling the size of my lambda packages.
> 
> One workaround I tried was to force the path of source map to a different folder. However this does not work for the bundle size report with multiple entry points as it is not compatible with qualifiers such as [file].
> 
> I also tried adding entries in a .gitignore file so that npm does not package them but that does not work either.
> 
> It would be great if I could just tell serverless webpack to ignore those files.
> 
> Thanks!

I have this same problem. It's wonderfully ironic that I wanted to analyze the bundle size to make it smaller, but the `report.html` doubled it's size!

**Comment by MikeRippon** [comment]
That seems to fix it for me on v5.5.0 thanks!

```
custom:
  webpack:
    excludeRegex: report\.html
```
