### ISSUE TITLE
Transitive dependencies not honoured by forceExclude

### ISSUE THREAD

**Issue by clar-cmp** [serverless-heaven/serverless-webpack#595]
# This is a Bug Report

## Description

Steps to reproduce:
1. I `forceExclude: - aws-sdk`
2. It is not forcibly removed from the bundle

Basically, I have a non-dev dependency which depends on `aws-sdk` and thus needs access to the SDK. Looking at the code on master right now, transitive dependencies are not removed when bundling. When I force-exclude a package, I want to completely remove it from the bundle.

**Comment by danrivett** [comment]
Not sure if the root cause is the same, but I added a comment to an older related issue [here](https://github.com/serverless-heaven/serverless-webpack/issues/305#issuecomment-653789983), which may help at least until it's been determined if there's a bug with `serverless-webpack` or not, as it's not clear to me.

**Comment by clar-cmp** [comment]
Looks like this is a duplicate of #306.
