### ISSUE TITLE
Custom runtime not workig for deployment of single function

### ISSUE THREAD

**Issue by rgruenewald** [serverless-heaven/serverless-webpack#755]
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?
`serverless deploy function -f functionName` always triggers the "serverless-webpack" plugin even when the runtime is not "nodejs".
* What did you expect should have happened?
serverless-webpack should not trigger on non nodejs runtimes (e.g. python)

The issue resides in within "lib/validate.js". The pull request (https://github.com/serverless-heaven/serverless-webpack/pull/579/files) applied the custom runtime only for "serverless deploy" but not for "serverless deploy function -f".

Similar or dependent issue(s):
* #579 

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.4.0
* ***Webpack version you're using***: 4.46.0
* ***Serverless Framework Version you're using***: 2.31.0
* ***Operating System***: Amazon Linux v2
* ***Stack Trace (if available)***:

**Comment by j0k3r** [comment]
I'm wondering if this could be fixed by https://github.com/serverless-heaven/serverless-webpack/pull/808

**Comment by j0k3r** [comment]
Could you test again using the 5.5.1? Thanks 🙏

**Comment by chrisweidya** [comment]
I ran into this problem too in 5.5.1. Not sure if I missed any configs I could've set. I am trying to have one function run on go and the rest on nodejs.

`serverless deploy`  runs fine as `serverless-webpack` will filter out non-node functions now and consolidate entries to only nodejs runtimes. But if the only function's runtime is not nodejs or if you run `serverless deploy function -f nonNodejsFunctionName`, `slsw.entries` (which I am using in webpack config) will result in an empty object and this will cause webpack to error due to an empty entry field.

I modified the code a bit on my end and got it to work by checking for empty entries after the 'validate' stage and exiting the next stages early. However I think not having `serverless-webpack` run at all may be a better solution in these cases.

**Comment by j0k3r** [comment]
Can you try to use this PR #879 and test it?

**Comment by chrisweidya** [comment]
Didn't seem to work :( 

The error would occur at Line 90 in `compile.js` as it loads in the empty `{}` object from webpack config.

I tried this and it seemed to work, tested on my own single go/node functions:
```js

// index.js, line 108
'before:deploy:function:packageFunction': () => {
  if (this.options.function) {
    const runtime = this.serverless.service.getFunction(this.options.function).runtime;
    if (isNodeRuntime(runtime))
      return BbPromise.bind(this)
        .then(() => this.serverless.pluginManager.spawn('webpack:validate'))
        .then(() => this.serverless.pluginManager.spawn('webpack:compile'))
        .then(() => this.serverless.pluginManager.spawn('webpack:package'))
  }
},
```
Not sure if this affects anything else though

**Comment by j0k3r** [comment]
In fact, it might the fastest solution. I tried to hook into validate, compile & package but it adds a lot overhead.
